import { Resend } from 'resend';

// ─── Why this file exists ─────────────────────────────────────────────────────
//
// Instead of importing Resend directly in every service that needs to send an
// email, we centralise all email logic here. This means:
//   1. If we ever switch from Resend to another provider, we only change THIS file.
//   2. Every email has consistent styling (our brand template).
//   3. Services stay clean — they just call `sendOtpEmail(...)`, not deal with
//      HTML templates or API details.
//
// ─────────────────────────────────────────────────────────────────────────────

// Create one Resend client. It reads the API key from the environment variable
// we set in .env. If the key is missing, it will throw when you try to send.
const resend = new Resend(process.env.EMAIL_API_KEY);

// The "from" address — also comes from .env so it's easy to change.
const FROM_ADDRESS = process.env.EMAIL_FROM || 'onboarding@resend.dev';
const STORE_NAME = 'Center ElSayad';

// ─── Email Templates ──────────────────────────────────────────────────────────

/**
 * Builds the HTML string for the OTP email.
 *
 * We're using a plain HTML string here (not a React template or Handlebars)
 * to keep things simple — this is totally standard for transactional emails.
 */
function buildOtpEmailHtml(code: string): string {
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Your ${STORE_NAME} Reset Code</title>
    </head>
    <body style="margin:0;padding:0;background:#f4f4f5;font-family:Arial,sans-serif;">
      <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f5;padding:40px 0;">
        <tr>
          <td align="center">
            <table width="520" cellpadding="0" cellspacing="0"
              style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">

              <!-- Header -->
              <tr>
                <td style="background:#c0392b;padding:32px;text-align:center;">
                  <h1 style="color:#ffffff;margin:0;font-size:24px;letter-spacing:1px;">
                    ${STORE_NAME}
                  </h1>
                </td>
              </tr>

              <!-- Body -->
              <tr>
                <td style="padding:40px 48px;">
                  <h2 style="color:#1a1a1a;font-size:20px;margin:0 0 12px;">Password Reset</h2>
                  <p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 28px;">
                    We received a request to reset your password. Use the code below —
                    it expires in <strong>15 minutes</strong>.
                  </p>

                  <!-- OTP Box -->
                  <div style="background:#f4f4f5;border-radius:8px;padding:24px;text-align:center;margin-bottom:28px;">
                    <span style="font-size:42px;font-weight:700;letter-spacing:12px;color:#c0392b;font-family:monospace;">
                      ${code}
                    </span>
                  </div>

                  <p style="color:#888;font-size:13px;margin:0;">
                    If you didn't request this, you can safely ignore this email.
                    Your password won't change.
                  </p>
                </td>
              </tr>

              <!-- Footer -->
              <tr>
                <td style="padding:20px 48px;border-top:1px solid #eee;text-align:center;">
                  <p style="color:#aaa;font-size:12px;margin:0;">
                    © ${new Date().getFullYear()} ${STORE_NAME}. All rights reserved.
                  </p>
                </td>
              </tr>

            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
}

// ─── Public Functions ─────────────────────────────────────────────────────────

/**
 * Sends a password reset OTP email.
 *
 * @param to    - The recipient's email address (e.g. "user@example.com")
 * @param code  - The 6-digit OTP generated by the auth service
 *
 * Throws if the Resend API returns an error (e.g. invalid API key).
 * The caller (auth.service.ts) should catch this and handle it gracefully.
 */
export async function sendOtpEmail(to: string, code: string): Promise<void> {
  const { error } = await resend.emails.send({
    from: FROM_ADDRESS,
    to,
    subject: `${code} is your ${STORE_NAME} verification code`,
    html: buildOtpEmailHtml(code),
  });

  if (error) {
    // Re-throw as a standard Error so the caller can catch it.
    throw new Error(`Email send failed: ${error.message}`);
  }

  console.log(`📧 OTP email sent to ${to}`);
}
